name: Java CI with Maven
on:
  schedule:
    - cron: '0 01 * * *'
      timezone: Asia/Shanghai
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.382+5'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        env:
          OWNER_REPO: ${{github.repository}}
          MY_GITHUB_API_TOKEN: ${{github.token}}
          CMG_PASSWORD: ${{secrets.CMG_PASSWORD}}
          CMG_NAME: ${{secrets.CMG_NAME}}
          REPO_PATH: src/main/resources
          SUB_ACCOUNT: ${{secrets.SUB_ACCOUNT}}
        run: mvn -B -q package --file pom.xml
